spring.application.name=saludvida

spring.datasource.url=jdbc:postgresql://localhost:5432/SaludVida
spring.datasource.username=postgres
spring.datasource.password=170901das

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
